//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationWithDatabase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public Nullable<System.DateTime> Issued { get; set; }
        public string CouponCode { get; set; }
    }
}
